In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/2014-15_To_2016-17_School-_Level_NYC_Regents_Report_For_All_Variables.csv')

In [ ]:
# After seeing the head of the data on a previous notebook, I selected just 1 school to analyze the data.
df[df['School Name'] == '47 The American Sign Language and English Secondar']

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR
281,02M047,47 The American Sign Language and English Seco...,High school,Algebra2/Trigonometry,2015,14,53,9,64.3,5,35.7,1,7.1,1,7.1
282,02M047,47 The American Sign Language and English Seco...,High school,Algebra2/Trigonometry,2016,14,34.6,14,100,0,0,0,0,0,0
283,02M047,47 The American Sign Language and English Seco...,High school,Algebra2/Trigonometry,2017,8,38.4,8,100,0,0,0,0,0,0
284,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2015,66,57.6,48,72.7,18,27.3,0,0,2,3
285,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2016,28,58.9,16,57.1,12,42.9,0,0,5,17.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141024,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2016,31,70.8,11,35.5,20,64.5,10,32.3,na,na
141025,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2016,2,s,s,s,s,s,s,s,na,na
141026,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,10,s,s,s,s,s,s,s,na,na
141027,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,26,70.7,11,42.3,15,57.7,9,34.6,na,na
141028,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,1,s,s,s,s,s,s,s,na,na

In [ ]:
# From the school selected I want to filter the data just by the year 2017 as I just want to see the results of that year.
df[(df['School Name']== '47 The American Sign Language and English Secondar') & (df['Year'] == 2017)]

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR
283,02M047,47 The American Sign Language and English Seco...,High school,Algebra2/Trigonometry,2017,8,38.4,8,100,0,0,0,0,0,0
286,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,119,69.3,27,22.7,92,77.3,13,10.9,70,58.8
288,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra2,2017,16,63.9,7,43.8,9,56.3,0,0,9,56.3
291,02M047,47 The American Sign Language and English Seco...,High school,Common Core English,2017,47,75.9,6,12.8,41,87.2,25,53.2,33,70.2
294,02M047,47 The American Sign Language and English Seco...,High school,Common Core Geometry,2017,29,56.6,21,72.4,8,27.6,0,0,4,13.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141013,02M047,47 The American Sign Language and English Seco...,High school,Physical Settings/Earth Science,2017,33,61.8,20,60.6,13,39.4,4,12.1,na,na
141014,02M047,47 The American Sign Language and English Seco...,High school,Physical Settings/Earth Science,2017,2,s,s,s,s,s,s,s,na,na
141026,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,10,s,s,s,s,s,s,s,na,na
141027,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,26,70.7,11,42.3,15,57.7,9,34.6,na,na
141028,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,1,s,s,s,s,s,s,s,na,na

In [ ]:
#Here I was looking to see if we have data from 2010 to present, just to have an idea of how many years the results are presented.
df[(df['School Name']== '47 The American Sign Language and English Secondar') & (df['Year'] >= 2010)]

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Number Scoring 80 or Above,Percent Scoring 80 or Above
281,02M047,47 The American Sign Language and English Seco...,High school,Algebra2/Trigonometry,2015,14,1,7.1
282,02M047,47 The American Sign Language and English Seco...,High school,Algebra2/Trigonometry,2016,14,0,0
283,02M047,47 The American Sign Language and English Seco...,High school,Algebra2/Trigonometry,2017,8,0,0
284,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2015,66,0,0
285,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2016,28,0,0
...,...,...,...,...,...,...,...,...
141024,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2016,31,10,32.3
141025,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2016,2,s,s
141026,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,10,s,s
141027,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,26,9,34.6
141028,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,1,s,s

In [ ]:
#Removing columns that I do not need for my analysis.
drop_cols = ['Mean Score', 'Number Scoring Below 65', 'Percent Scoring Below 65', 'Number Scoring 65 or Above', 'Percent Scoring 65 or Above', 'Number Scoring CR', 'Percent Scoring CR' ]
df.drop(drop_cols, inplace = True, axis=1)

KeyError: "['Mean Score', 'Number Scoring Below 65', 'Percent Scoring Below 65', 'Number Scoring 65 or Above', 'Percent Scoring 65 or Above', 'Number Scoring CR', 'Percent Scoring CR'] not found in axis"

In [ ]:
#Back to see the data only from 2017.
df[(df['School Name']== '47 The American Sign Language and English Secondar') & (df['Year'] == 2017)]

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Number Scoring 80 or Above,Percent Scoring 80 or Above
283,02M047,47 The American Sign Language and English Seco...,High school,Algebra2/Trigonometry,2017,8,0,0
286,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,119,13,10.9
288,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra2,2017,16,0,0
291,02M047,47 The American Sign Language and English Seco...,High school,Common Core English,2017,47,25,53.2
294,02M047,47 The American Sign Language and English Seco...,High school,Common Core Geometry,2017,29,0,0
...,...,...,...,...,...,...,...,...
141013,02M047,47 The American Sign Language and English Seco...,High school,Physical Settings/Earth Science,2017,33,4,12.1
141014,02M047,47 The American Sign Language and English Seco...,High school,Physical Settings/Earth Science,2017,2,s,s
141026,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,10,s,s
141027,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,26,9,34.6
141028,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,1,s,s

In [ ]:
#Since I noticed that my data has inconsistent information within the columns I was trying to determine what the s means.
df[(df['School Name']== '47 The American Sign Language and English Secondar') & (df['Year'] == 2017) & (df['Percent Scoring 80 or Above'] != 's')]

In [ ]:
#Groping data by Regents Exam, year with aggregate percent scoring 80 of above as I want to focus my comparison on this last item.
df2 = df1.groupby(['School DBN','School Level','Regents Exam','Year']).agg({'Percent Scoring 80 or Above': 'sum',})
print(df2)

                                                                   Percent Scoring 80 or Above
School DBN School Level Regents Exam                    Year
02M047     High school  Algebra2/Trigonometry           2017                                00
                        Common Core Algebra             2017     10.912.64.212.412.26.95.114.3
                        Common Core Algebra2            2017                                00
                        Common Core English             2017  53.265.716.744.481.857.141.758.1
                        Common Core Geometry            2017                         000000000
                        Global History and Geography    2017            182502022.75.929.412.8
                        Living Environment              2017       9.311.90013.209.87.75.912.5
                        Physical Settings/Earth Science 2017    10.910.911.11410.612.510.512.1
                        U.S. History and Government     2017         29.739.3029.634.512.534.6

In [ ]:
#Looking for results that don’t have actual values and not s.
df[(df['School Name']== '47 The American Sign Language and English Secondar') & (df['Year'] == 2017) & (df['Percent Scoring 80 or Above'] != 's')]

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Number Scoring 80 or Above,Percent Scoring 80 or Above
283,02M047,47 The American Sign Language and English Seco...,High school,Algebra2/Trigonometry,2017,8,0,0
286,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,119,13,10.9
288,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra2,2017,16,0,0
291,02M047,47 The American Sign Language and English Seco...,High school,Common Core English,2017,47,25,53.2
294,02M047,47 The American Sign Language and English Seco...,High school,Common Core Geometry,2017,29,0,0
...,...,...,...,...,...,...,...,...
140999,02M047,47 The American Sign Language and English Seco...,High school,Living Environment,2017,17,1,5.9
141000,02M047,47 The American Sign Language and English Seco...,High school,Living Environment,2017,32,4,12.5
141012,02M047,47 The American Sign Language and English Seco...,High school,Physical Settings/Earth Science,2017,19,2,10.5
141013,02M047,47 The American Sign Language and English Seco...,High school,Physical Settings/Earth Science,2017,33,4,12.1
141027,02M047,47 The American Sign Language and English Seco...,High school,U.S. History and Government,2017,26,9,34.6

In [ ]:
#Filtering by just one topic of the Regents Exam.
df[(df['School Name']== '47 The American Sign Language and English Secondar') & (df['Year'] == 2017) & (df['Percent Scoring 80 or Above'] != 's') & (df['Regents Exam'] == 'Common Core Algebra')]

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Number Scoring 80 or Above,Percent Scoring 80 or Above
286,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,119,13,10.9
19972,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,95,12,12.6
19973,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,24,1,4.2
54938,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,89,11,12.4
103419,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,90,11,12.2
103420,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,29,2,6.9
140933,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,39,2,5.1
140934,02M047,47 The American Sign Language and English Seco...,High school,Common Core Algebra,2017,70,10,14.3

In [ ]:
#Realized the data type under percent scoring 80 or above is in str was trying to convert it to a number.
df1['Percent Scoring 80 or Above'] = pd.to_numeric(df1['Percent Scoring 80 or Above'])

/tmp/ipykernel_5834/1737870358.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Percent Scoring 80 or Above'] = pd.to_numeric(df1['Percent Scoring 80 or Above'])

In [ ]:
#My intention was to initially select a school and within that school select one or two years to compare the results above 80 percent. Then select another school to do the same comparison of results for the same years. I was unable to complete the project as I was unable to convert some of the data from str to numerical values. I was unable to figure out what I was doing wrong to move forward with the project.